export const GET_BANNERS = 'GET_BANNERS';
export const GET_BANNERS_LOADING = 'GET_BANNERS_LOADING';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_BANNERS_ERROR = 'GET_BANNERS_ERROR';

export const GET_TOP_TRACKS = 'GET_TOP_TRACKS';
export const GET_TOP_TRACKS_LOADING = 'GET_TOP_TRACKS_LOADING';
export const GET_TOP_TRACKS_SUCCESS = 'GET_TOP_TRACKS_SUCCESS';
export const GET_TOP_TRACKS_ERROR = 'GET_TOP_TRACKS_ERROR';

export const GET_RECENTLY_ADDED_TRACKS = 'GET_RECENTLY_ADDED_TRACKS';
export const GET_RECENTLY_ADDED_TRACKS_LOADING = 'GET_RECENTLY_ADDED_TRACKS_LOADING';
export const GET_RECENTLY_ADDED_TRACKS_SUCCESS = 'GET_RECENTLY_ADDED_TRACKS_SUCCESS';
export const GET_RECENTLY_ADDED_TRACKS_ERROR = 'GET_RECENTLY_ADDED_TRACKS_ERROR';

export const GET_UPCOMING_EVENTS = 'GET_UPCOMING_EVENTS';
export const GET_UPCOMING_EVENTS_LOADING = 'GET_UPCOMING_EVENTS_LOADING';
export const GET_UPCOMING_EVENTS_SUCCESS = 'GET_UPCOMING_EVENTS_SUCCESS';
export const GET_UPCOMING_EVENTS_ERROR = 'GET_UPCOMING_EVENTS_ERROR';

export const GET_RECENT_BLOGS = 'GET_RECENT_BLOGS';
export const GET_RECENT_BLOGS_LOADING = 'GET_RECENT_BLOGS_LOADING';
export const GET_RECENT_BLOGS_SUCCESS = 'GET_RECENT_BLOGS_SUCCESS';
export const GET_RECENT_BLOGS_ERROR = 'GET_RECENT_BLOGS_ERROR';
