export const SET_SELECTED_MENU_ITEM_ID = 'SET_SELECTED_MENU_ITEM_ID';
export const TOGGLE_SIDEBAR_FOLDED = 'TOGGLE_SIDEBAR_FOLDED';
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY';
export const TOGGLE_SEARCHBAR_VISIBILITY = 'TOGGLE_SEARCHBAR_VISIBILITY';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
